name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: kondensmelkcr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build Docker image
      run: |
        docker build -t <your-acr-name>.azurecr.io/<image-name>:latest .
    
    - name: Push Docker image to Azure Container Registry
      run: |
        docker push kondensmelkcr.azurecr.io/nginx-image:v2
